export const uiText = {
  "zh-TW": {
    title: "文字分析測試 UI",
    placeholder: "輸入要分析的文字（德文單字或句子）...",
    submit: "查詢",
    loading: "查詢中...",
    result: "分析結果",
    wordMode: "單字分析",
    sentenceMode: "句子分析",
    length: "字元數",
    isLong: "是否偏長",
    wordCard: {
      headerMain: "單字總覽",
      sectionGrammar: "語法資訊",
      sectionMeaning: "語意說明",
      sectionExample: "例句",
      sectionExampleTranslation: "翻譯",
      sectionNotes: "補充說明",
      labelPos: "詞性",
      labelGender: "性別",
      labelPlural: "複數",
      labelBaseForm: "原形",
      labelDefinition: "釋義",
      labelExample: "例句",
      labelNotes: "註解",

      // 名詞四格表標題
      caseTableTitle: "四格變化（單數・定冠詞）",

      // 句型結構／文法選項（例句區塊用）
      grammarOptionsLabel: "句型結構",
      grammarToggleLabel: "調整句型",
      grammarCaseLabel: "格位",

      // ★ 已修改：加入德文格名
      grammarCaseNomLabel: "主格 (Nominativ)",      // ★
      grammarCaseAkkLabel: "受格 (Akkusativ)",      // ★
      grammarCaseDatLabel: "與格 (Dativ)",          // ★
      grammarCaseGenLabel: "屬格 (Genitiv)",        // ★

      grammarArticleLabel: "冠詞",
      grammarArticleDefLabel: "定冠詞",
      grammarArticleIndefLabel: "不定冠詞",
      grammarArticleNoneLabel: "無冠詞",
      refreshExamplesTooltipLabel: "重新產生例句",

      posLocalNameMap: {
        Nomen: "名詞",
        Verb: "動詞",
        Adjektiv: "形容詞",
        Adverb: "副詞",
        Artikel: "冠詞",
        Pronomen: "代名詞",
        Präposition: "介系詞",
        Konjunktion: "連接詞",
        Numerale: "數詞",
        Interjektion: "感嘆詞",
        Partikel: "語氣詞／功能小詞",
        Hilfsverb: "助動詞",
        Modalverb: "情態動詞",
        Reflexivpronomen: "反身代名詞",
        Possessivpronomen: "所有格代名詞",
      },
    },
    grammarCard: {
      title: "句子語法檢查",
      correct: "✔ 句子語法正確，沒有明顯錯誤。",
      incorrect: "⚠ 發現可能的語法問題：",
      labelOriginal: "原句片段",
      labelSuggestion: "建議改法",
      labelExplanation: "說明",
    },
  },

  en: {
    title: "Text Analysis UI",
    placeholder: "Enter a German word or sentence...",
    submit: "Search",
    loading: "Searching...",
    result: "Result",
    wordMode: "Word Analysis",
    sentenceMode: "Sentence Analysis",
    length: "Length",
    isLong: "Long?",
    wordCard: {
      headerMain: "Word Overview",
      sectionGrammar: "Grammar",
      sectionMeaning: "Meaning",
      sectionExample: "Example",
      sectionExampleTranslation: "Translation",
      sectionNotes: "Notes",
      labelPos: "Part of Speech",
      labelGender: "Gender",
      labelPlural: "Plural",
      labelBaseForm: "Base Form",
      labelDefinition: "Definition",
      labelExample: "Example",
      labelNotes: "Notes",

      caseTableTitle: "Cases – Singular (with definite article)",

      grammarOptionsLabel: "Sentence pattern",
      grammarToggleLabel: "Adjust sentence pattern",
      grammarCaseLabel: "Case",
      grammarCaseNomLabel: "Nominative",
      grammarCaseAkkLabel: "Accusative",
      grammarCaseDatLabel: "Dative",
      grammarCaseGenLabel: "Genitive",
      grammarArticleLabel: "Article",
      grammarArticleDefLabel: "Definite article",
      grammarArticleIndefLabel: "Indefinite article",
      grammarArticleNoneLabel: "No article",
      refreshExamplesTooltipLabel: "Regenerate examples",

      posLocalNameMap: {
        Nomen: "noun",
        Verb: "verb",
        Adjektiv: "adjective",
        Adverb: "adverb",
        Artikel: "article",
        Pronomen: "pronoun",
        Präposition: "preposition",
        Konjunktion: "conjunction",
        Numerale: "numeral",
        Interjektion: "interjection",
        Partikel: "particle",
        Hilfsverb: "auxiliary verb",
        Modalverb: "modal verb",
        Reflexivpronomen: "reflexive pronoun",
        Possessivpronomen: "possessive pronoun",
      },
    },
    grammarCard: {
      title: "Sentence Grammar Check",
      correct: "✔ The sentence looks grammatically correct.",
      incorrect: "⚠ Potential grammar issues:",
      labelOriginal: "Original",
      labelSuggestion: "Suggestion",
      labelExplanation: "Explanation",
    },
  },

  "zh-CN": {
    title: "文字分析界面",
    placeholder: "输入要分析的德语单词或句子...",
    submit: "查询",
    loading: "查询中...",
    result: "分析结果",
    wordMode: "单词分析",
    sentenceMode: "句子分析",
    length: "字符数",
    isLong: "是否较长",
    wordCard: {
      headerMain: "单词总览",
      sectionGrammar: "语法信息",
      sectionMeaning: "语义说明",
      sectionExample: "例句",
      sectionExampleTranslation: "翻译",
      sectionNotes: "补充说明",
      labelPos: "词性",
      labelGender: "性别",
      labelPlural: "复数",
      labelBaseForm: "原形",
      labelDefinition: "释义",
      labelExample: "例句",
      labelNotes: "注释",

      caseTableTitle: "四格变化（单数・定冠词）",

      grammarOptionsLabel: "句型结构",
      grammarToggleLabel: "调整句型",
      grammarCaseLabel: "格位",
      grammarCaseNomLabel: "主格 (Nominativ)",   // ★
      grammarCaseAkkLabel: "宾格 (Akkusativ)", // ★
      grammarCaseDatLabel: "与格 (Dativ)",      // ★
      grammarCaseGenLabel: "属格 (Genitiv)",    // ★

      grammarArticleLabel: "冠词",
      grammarArticleDefLabel: "定冠词",
      grammarArticleIndefLabel: "不定冠词",
      grammarArticleNoneLabel: "无冠词",
      refreshExamplesTooltipLabel: "重新生成例句",

      posLocalNameMap: {
        Nomen: "名词",
        Verb: "动词",
        Adjektiv: "形容词",
        Adverb: "副词",
        Artikel: "冠词",
        Pronomen: "代词",
        Präposition: "介词",
        Konjunktion: "连词",
        Numerale: "数词",
        Interjektion: "感叹词",
        Partikel: "语气词／功能词",
        Hilfsverb: "助动词",
        Modalverb: "情态动词",
        Reflexivpronomen: "反身代词",
        Possessivpronomen: "物主代词",
      },
    },
    grammarCard: {
      title: "句子语法检查",
      correct: "✔ 句子语法正确，没有明显错误。",
      incorrect: "⚠ 发现可能的语法问题：",
      labelOriginal: "原句片段",
      labelSuggestion: "建议修改",
      labelExplanation: "说明",
    },
  },

  ar: {
    title: "واجهة تحليل النص",
    placeholder: "اكتب كلمة أو جملة ألمانية للتحليل...",
    submit: "بحث",
    loading: "جارٍ البحث...",
    result: "نتيجة التحليل",
    wordMode: "تحليل الكلمة",
    sentenceMode: "تحليل الجملة",
    length: "عدد الأحرف",
    isLong: "طويل؟",
    wordCard: {
      headerMain: "نظرة عامة على الكلمة",
      sectionGrammar: "معلومات القواعد",
      sectionMeaning: "المعنى",
      sectionExample: "مثال",
      sectionExampleTranslation: "الترجمة",
      sectionNotes: "ملاحظات",
      labelPos: "نوع الكلمة",
      labelGender: "الجنس",
      labelPlural: "الجمع",
      labelBaseForm: "الصيغة الأساسية",
      labelDefinition: "التعريف",
      labelExample: "مثال",
      labelNotes: "ملاحظات",

      caseTableTitle: "الحالات – المفرد (مع أداة التعريف)",

      grammarOptionsLabel: "بنية الجملة",
      grammarToggleLabel: "تعديل بنية الجملة",
      grammarCaseLabel: "الحالة الإعرابية",
      grammarCaseNomLabel: "مرفوع (Nominativ)",
      grammarCaseAkkLabel: "منصوب (Akkusativ)",
      grammarCaseDatLabel: "مجرور (Dativ)",
      grammarCaseGenLabel: "مضاف إليه (Genitiv)",
      grammarArticleLabel: "أداة التعريف",
      grammarArticleDefLabel: "مع أداة التعريف",
      grammarArticleIndefLabel: "نكرة",
      grammarArticleNoneLabel: "بدون أداة",
      refreshExamplesTooltipLabel: "توليد أمثلة جديدة",

      posLocalNameMap: {
        Nomen: "اسم",
        Verb: "فعل",
        Adjektiv: "صفة",
        Adverb: "حال",
        Artikel: "أداة تعريف",
        Pronomen: "ضمير",
        Präposition: "حرف جر",
        Konjunktion: "أداة ربط",
        Numerale: "عدد",
        Interjektion: "أداة تعجب",
        Partikel: "أداة",
        Hilfsverb: "فعل مساعد",
        Modalverb: "فعل modal / ناقص",
        Reflexivpronomen: "ضمير انعكاسي",
        Possessivpronomen: "ضمير ملكية",
      },
    },
    grammarCard: {
      title: "فحص قواعد الجملة",
      correct: "✔ تبدو الجملة صحيحة نحوياً。",
      incorrect: "⚠ توجد مشكلات محتملة في القواعد:",
      labelOriginal: "النص الأصلي",
      labelSuggestion: "الاقتراح",
      labelExplanation: "التفسير",
    },
  },
};
